name: 'release'
on:
  push:
    branches:
      - main
      - 'releases/*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0     
    - name: Conventional Changelog Action
      uses: TriPSs/conventional-changelog-action@v5
      with:
        github-token: ${{ secrets.github_token }}
        git-message: 'chore(release): {version}'
        git-user-name: 'Markus Linke'
        git-user-email: 'markus.linke@linke.de'
        preset: 'angular'
        tag-prefix: 'v'
        output-file: 'CHANGELOG.md'
        release-count: '10'
        version-file: './VERSION.yml' 
        version-path: 'version'
        skip-on-empty: 'false'
        skip-version-file: 'false'
        skip-commit: 'false'
        # git-branch: 'my-maintenance-branch'